# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Try out "interactive-mode"
os: Windows Server 2012 R2

# build version format
version: "{build}"

# Set a known clone folder
clone_folder: c:\projects\nodegit

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "John Doe"
  - git config --global user.email johndoe@example.com

# what combinations to test
environment:
  matrix:
    # Node.js
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    # io.js
    - nodejs_version: "1.4.3"

matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: "0.10"
    - nodejs_version: "1.4.3"

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET JOBS=4
  - cmd: SET BUILD_ONLY=true
  - cmd: SET GIT_SSH=c:\projects\nodegit\vendor\plink.exe
  - ps: Start-Process c:\projects\nodegit\vendor\pageant.exe c:\projects\nodegit\vendor\private.ppk
  - cmd: npm install -g node-gyp
  - npm install --msvs_version=2013

test_script:
  - node --version
  - npm --version
  - cmd: npm test

build: off

branches:
  only:
    - master
    - v0.3
