# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
project_id: "e5a5q75l9yfhnfv2"

# build version format
version: "{build}"

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.8

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install

build: off
